export const mode = Object.freeze({
  REPEAT: 'REPEAT',
  LOOP: 'LOOP',
  SHUFFLE: 'SHUFFLE',
});

export const globalPlayer = Object.freeze({
  CHANGE_MODE: 'CHANGE_MODE',
  CHANGE_IS_PLAYING: 'CHANGE_IS_PLAYING',
  CHANGE_MUSIC: 'CHANGE_MUSIC',
  CHANGE_MUSICS: 'CHANGE_MUSICS',
  GET_LYRICS_REQUEST: 'GET_LYRICS_REQUEST',
  GET_LYRICS_FAILURE: 'GET_LYRICS_FAILURE',
  GET_LYRICS_SUCCESS: 'GET_LYRICS_SUCCESS',
});
